In [11]:
import torch

from koopmann.models import LowRankKoopmanAutoencoder

In [12]:
lorakae = LowRankKoopmanAutoencoder(rank=10, k_steps=1, in_features=784, latent_features=512)
lora_down = lorakae.components.koopman_matrix.components.lora_down
lora_up = lorakae.components.koopman_matrix.components.lora_up

In [13]:
x = torch.randn((1, 512))

resa = x @ lorakae.koopman_weights.T
resb = lora_up(lora_down(x))

In [14]:
resa[0, :10]

tensor([ 0.0417,  0.0531, -0.0057, -0.0387, -0.0839,  0.0192, -0.0123, -0.0044,
        -0.0262, -0.0759], grad_fn=<SliceBackward0>)

In [15]:
resb[0, :10]

tensor([ 0.0417,  0.0531, -0.0057, -0.0387, -0.0839,  0.0192, -0.0123, -0.0044,
        -0.0262, -0.0759], grad_fn=<SliceBackward0>)

In [16]:
lora_down.weight

Parameter containing:
tensor([[-0.0359, -0.0408,  0.0135,  ..., -0.0069,  0.0161, -0.0389],
        [ 0.0151, -0.0420,  0.0081,  ...,  0.0044, -0.0027,  0.0201],
        [-0.0431, -0.0120,  0.0395,  ..., -0.0342,  0.0392,  0.0077],
        ...,
        [-0.0081, -0.0341,  0.0013,  ...,  0.0023, -0.0413,  0.0061],
        [-0.0036,  0.0140,  0.0265,  ...,  0.0126,  0.0346,  0.0195],
        [ 0.0354, -0.0385,  0.0173,  ...,  0.0424,  0.0441, -0.0171]],
       requires_grad=True)

In [17]:
lora_up.weight.t()

tensor([[-0.0359, -0.0408,  0.0135,  ..., -0.0069,  0.0161, -0.0389],
        [ 0.0151, -0.0420,  0.0081,  ...,  0.0044, -0.0027,  0.0201],
        [-0.0431, -0.0120,  0.0395,  ..., -0.0342,  0.0392,  0.0077],
        ...,
        [-0.0081, -0.0341,  0.0013,  ...,  0.0023, -0.0413,  0.0061],
        [-0.0036,  0.0140,  0.0265,  ...,  0.0126,  0.0346,  0.0195],
        [ 0.0354, -0.0385,  0.0173,  ...,  0.0424,  0.0441, -0.0171]],
       grad_fn=<TBackward0>)